Room config enhancement and bugfixes
wario-land/WL4Editor pull request #316
Opened 2020-12-22 02:30 UTC by shinespeciall

Fix #315 
now Layer 0 and Layer 2 can have data recovery when undo disable operation on them (layer 0 is a bit different and comlicated, but the data recovery still work)

2020-12-22 07:35 UTC, Goldensunboy requested changes

2020-12-22 07:35 UTC, Goldensunboy commented on WL4EditorWindow.cpp
> +            memset(tmpLayerdata2, 0, datasize2);
the memset is useless

2020-12-22 07:35 UTC, Goldensunboy commented on WL4EditorWindow.cpp
> +            memset(tmpLayerdata2, 0, datasize2);
and the one in the next if clause

2020-12-22 07:35 UTC, Goldensunboy commented on WL4EditorWindow.cpp
> +            memset(tmpLayerdata2, 0, datasize2);
also lines 612 and 622

2020-12-22 08:26 UTC, shinespeciall commented on WL4EditorWindow.cpp
> +            memset(tmpLayerdata2, 0, datasize2);
done.

2020-12-23 01:58 UTC, Goldensunboy approved these changes

2020-12-23 02:01 UTC, merged